#define IDCCHANGE                       3
#define IDD_COLORS                      101
#define IDC_COLORSLIST                  1000
#define IDAPPLY                         4
#define IDC_RED                         1001
#define IDC_GREEN                       1002
#define IDC_BLUE                        1003
#define IDC_COLOR                       1004
#define IDC_STATIC                      -1
